version: '3'

#Define services
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - backendNetwork
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - backendNetwork
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092, PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME= kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE= true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: redirect-service
      MYSQL_ROOT_PASSWORD: Sergi8010026
      MYSQL_USER: sergi
      MYSQL_PASSWORD: 1111
    ports:
      - 3306:3306
    volumes:
      - redirect-service:/var/lib/mysql
    networks:
      - backendNetwork

#Back-end Spring Boot Application
  redirect-service:
    image: adoptopenjdk/openjdk11
    container_name: redirect-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/redirect-service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - 8090:8090
    depends_on:
      - db
      - zookeeper
      - kafka
    volumes:
      - ./Url-Shortener-Backend/target/Url-Shortener-Backend-0.0.1-SNAPSHOT.jar:/application.jar
    command: [ "java", "-jar", "application.jar" ]
    networks:
      - backendNetwork
      - frontendNetwork

  #Front-end Angular Application
  angular:
    image: nginx:alpine
    container_name: angular
    ports:
      - 4200:90
    depends_on:
      - redirect-service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Url-Shortener-Angular/dist/Url-Shortener-Angular/:/usr/share/nginx/html
    networks:
      - frontendNetwork

#Volumes for DB data
volumes:
  redirect-service:

networks:
  backendNetwork:
  frontendNetwork:

